services:
  watch-that-picker-example:
    build:
      context: https://github.com/zugch/watch-that-picker.git
    container_name: watch-that-picker-example
    environment:
      - SCRAPE_URL=https://example.com
      - ELEMENT_SELECTOR=h1
      - CRON_EXPRESSION=*/1 * * * *
    command: ["python", "src/pick.py"]
  watch-that-picker-watch:
    build:
      context: https://github.com/zugch/watch-that-picker.git
    container_name: watch-that-picker-watch
    environment:
      - SCRAPE_URL=https://www.uhrzeit.org/atomuhr
      - ELEMENT_SELECTOR=.anzeige
      - CRON_EXPRESSION=*/2 * * * *
    command: ["python", "src/pick.py"]
