services:
  watch-that-example-picker:
    build:
#      context: .
      context: https://github.com/zugch/watch-that-picker.git
      dockerfile: docker/Dockerfile
    container_name: watch-that-example-picker
    volumes:
      - .:/app
    environment:
      - SCRAPE_URL=https://example.com
      - ELEMENT_SELECTOR=h1
      - CRON_EXPRESSION=*/1 * * * *
    command: ["python", "src/watch.py"]
  watch-that-watch-picker:
    build:
#      context: .
      context: https://github.com/zugch/watch-that-picker.git
      dockerfile: docker/Dockerfile
    container_name: watch-that-watch-picker
    volumes:
      - .:/app
    environment:
      - SCRAPE_URL=https://www.uhrzeit.org/atomuhr
      - ELEMENT_SELECTOR=.anzeige
      - CRON_EXPRESSION=*/2 * * * *
    command: ["python", "src/watch.py"]
